version: "3.1"

services:
  app:
    build: .
    ports:
      - "80:3009"
    links:
      - mongo
  mongo:
    build: ./docker/mongo
    restart: always
    ports:
      - "27017:27017"

networks:
  default:
    external:
      name: dogadore
