FROM mongo

ENV MONGO_INITDB_ROOT_USERNAME dogadore
ENV MONGO_INITDB_ROOT_PASSWORD dogadore

# To initialize Mongo on Docker Up
# ENV MONGO_INITDB_DATABASE admin
# ADD mongo-init.js /docker-entrypoint-initdb.d/
